# Generated by Django 4.2.7 on 2023-12-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_payment_mehthod_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_guest', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='no_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.guest'),
        ),
    ]
