# Generated by Django 4.2.7 on 2023-12-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_table_table_image_alter_table_number_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
